version: '3.3'

services:
  efilibrary-backend-staging:
    container_name: efilibrary-backend-staging
    image: ${IMAGE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_SERVER: staging-mysql
      DATABASE_NAME: efilibrarydb
      DATABASE_USER: root
      DATABASE_PASSWORD: '3c35281b8a5104e58c84'
      PORT: '3002'
      OIDC_AUTH_BACKLINK_URL: 'https://host.docker.internal:3000'
      OIDC_AUTH_REDIRECT_URL: 'https://localhost:3002'
    networks:
      - efilibrary
    ports:
      - 3002:3002

  efilibrary-mysql:
    image: mysql

    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      #- efilibrary-db:/var/lib/mysql

    environment:
      MYSQL_DATABASE: efilibrarydb
      MYSQL_USER: app
      MYSQL_PASSWORD: 'not_secure'
      MYSQL_ROOT_PASSWORD: 'not_secure_root_password'

    ports:
      - 3306:3306

    expose:
      - 3306

networks:
  efilibrary:
    external: true
