version: '3.3'

services:
  efilibrary-backend-staging:
    container_name: efilibrary-backend-staging
    image: ${IMAGE_NAME}
    build:
      context: .
      dockerfile: Dockerfile.staging
    env_file:
      - .env
    ports:
      - 3002:3002
