version: '3.3'

services:
  efilibrary-backend:
    build:
      context: .
      dockerfile: Dockerfile

    #    stdin_open: true

    environment:
      DATABASE_SERVER: efilibrary-mysql
      DATABASE_NAME: efilibrarydb
      DATABASE_USER: app
      DATABASE_PASSWORD: 'not_secure'
      OIDC_AUTH_BACKLINK_URL: 'http://notworking:80/backlink'
      OIDC_AUTH_REDIRECT_URL: 'http://notworking:80/redirect'
      PORT: 3002
    ports:
      - 3002:3002

  efilibrary-mysql:
    image: mysql

    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      #- efilibrary-db:/var/lib/mysql

    environment:
      MYSQL_DATABASE: efilibrarydb
      MYSQL_USER: app
      MYSQL_PASSWORD: 'not_secure'
      MYSQL_ROOT_PASSWORD: 'not_secure_root_password'

    ports:
      - 3306:3306

    expose:
      - 3306
#volumes:
#  efilibrary-db:
