version: '3.3'

services:
  efilibrary-backend-staging:
    container_name: efilibrary-backend-staging
    image: ${IMAGE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_SERVER: ${{secrets.DATABASE_SERVER}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}
      DATABASE_USER: ${{secrets.DATABASE_USER}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      PORT: ${{secrets.DATABASE_SERVER}}
      OIDC_AUTH_BACKLINK_URL: ${{secrets.OIDC_AUTH_BACKLINK_URL}}
      OIDC_AUTH_REDIRECT_URL: ${{secrets.OIDC_AUTH_REDIRECT_URL}}
    networks:
      - efilibrary
    ports:
      - 3002:3002
  
  efilibrary-mysql:
    image: mysql

    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      #- efilibrary-db:/var/lib/mysql

    environment:
      MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE}}
      MYSQL_USER: ${{secrets.MYSQL_USER}}
      MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
      MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}

    ports:
      - 3306:3306

    expose:
      - 3306

networks:
  efilibrary:
    external: true
