# see https://code.visualstudio.com/remote/advancedcontainers/connect-multiple-containers
# see https://github.com/0916dhkim/vscode-devcontainer-tutorial/blob/master/.devcontainer/docker-compose.yml

version: '3.3'

services:
  development:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspace

    stdin_open: true

    environment:

      DATABASE_SERVER: mysql
      DATABASE_NAME: efilibrarydb
      DATABASE_USER: app
      DATABASE_PASSWORD: 'not_secure'
      PORT: 3000

    ports:
      - 3000:3000

  mysql:
    image: mysql

    volumes:
      - ../sql:/docker-entrypoint-initdb.d
      - my-db:/var/lib/mysql

    environment:
      MYSQL_DATABASE: efilibrarydb
      MYSQL_USER: app
      MYSQL_PASSWORD: 'not_secure'
      MYSQL_ROOT_PASSWORD: 'not_secure_root_password'

    ports:
      - 3306:3306

    expose:
      - 3306

volumes:
  my-db:
