# see https://code.visualstudio.com/remote/advancedcontainers/connect-multiple-containers
# see https://github.com/0916dhkim/vscode-devcontainer-tutorial/blob/master/.devcontainer/docker-compose.yml

version: '3.3'

services:
  development:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspace

    stdin_open: true

    environment:
      MYSQL_SERVER: mysql
      MYSQL_DATABASE: efilibrarydb
      MYSQL_USER: app
      MYSQL_PASSWORD: 'not_secure'
      PORT: 3000

    ports:
      - 3000:3000

  mysql:
    image: mysql

    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password

    restart: always

    volumes:
      - ../sql:/docker-entrypoint-initdb.d
      - my-db:/var/lib/mysql

    environment:
      MYSQL_DATABASE: efilibrarydb
      MYSQL_USER: app
      MYSQL_PASSWORD: 'not_secure'
      MYSQL_ROOT_PASSWORD: 'not_secure_root_password'

    ports:
      - 3306:3306

    expose:
      - 3306

volumes:
  my-db:
