const DATABASE_SERVER = process.env.MYSQL_SERVER;
const DATABASE_NAME = process.env.MYSQL_DATABASE;
const DATABASE_USER = process.env.MYSQL_USER;
const DATABASE_PASSWORD = process.env.MYSQL_PASSWORD;

export { DATABASE_SERVER, DATABASE_NAME, DATABASE_USER, DATABASE_PASSWORD }