name: Deploy backend to staging

on:
  push:
    branches: ['development', 'gh-actions']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/libraryprojectgroup/library-project-backend:${{ github.sha }}
  DATABASE_SERVER: ${{  secrets.DATABASE_SERVER  }}
  DATABASE_NAME: ${{secrets.DATABASE_NAME}
  DATABASE_USER: ${{secrets.DATABASE_USER}}
  DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
  PORT: ${{secrets.DATABASE_SERVER}}
  OIDC_AUTH_BACKLINK_URL: ${{secrets.OIDC_AUTH_BACKLINK_URL}}
  OIDC_AUTH_REDIRECT_URL: ${{secrets.OIDC_AUTH_REDIRECT_URL}}
  MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE}}
  MYSQL_USER: ${{secrets.MYSQL_USER}}
  MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
  MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build image
        run: docker-compose -f docker-compose-staging.yml build
      - name: Log in to the container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: docker-compose -f docker-compose-staging.yml push
