name: Node.js CI

on:
  push:
    branches: ["main", "development", "back-end-robot-test"]
  pull_request:
    branches: ["main", "development"]

env:
  TESTUSERNAME: ${{ secrets.REACT_APP_TEST_EMAIL }}
  TESTPASSWORD: ${{ secrets.REACT_APP_TEST_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci
      - name: Check formatting
        run: npm run fmt:check
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r robot-dependencies.txt
      - name: Run services with docker-compose
        run: docker-compose up -d -f docker-compose-test.yml
      - name: Spin up backend
        run: npx wait-on --timeout 120000 http://localhost:3000/health || (docker-compose logs --tail=10000 && exit 2)
      - run: npm test
      - run: docker-compose down -f docker-compose-test.yml
