name: Node.js CI

on:
  push:
    branches: ["main", "development", "back-end-robot-test"]
  pull_request:
    branches: ["main", "development"]

env:
  TESTUSERNAME: ${{ secrets.REACT_APP_TEST_EMAIL }}
  TESTPASSWORD: ${{ secrets.REACT_APP_TEST_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - name: Check formatting
        run: npm run fmt:check
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r robot-dependencies.txt
      - run: docker-compose up -d
      - run: npm install -g wait-on
      - run: wait-on http://localhost:3000/health
      - run: npm test
      - run: docker-compose down
